# Generated by Django 4.2 on 2023-12-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, verbose_name='地址缩写')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '日志分类',
                'verbose_name_plural': '日志分类',
                'ordering': ('-order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='qq',
            field=models.CharField(blank=True, max_length=50, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=50, verbose_name='微信'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='标题')),
                ('slug', models.SlugField(max_length=120, unique_for_date='created_time', verbose_name='地址缩写')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='图片')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('tags', models.CharField(max_length=200, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('flag', models.BooleanField(default=False, verbose_name='标记')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布')], default='draft', max_length=120, verbose_name='状态')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '博文日志',
                'verbose_name_plural': '博文日志',
                'ordering': ('-created_time',),
            },
        ),
    ]
