# Generated by Django 4.2 on 2023-12-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='用户名')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='IP')),
                ('body', models.TextField(verbose_name='正文')),
                ('active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post', verbose_name='日志评论')),
            ],
            options={
                'verbose_name': '日志评论',
                'verbose_name_plural': '日志评论',
                'ordering': ('-created_time',),
            },
        ),
    ]
