# Generated by Django 4.2 on 2023-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slide_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=120, verbose_name='链接'),
        ),
    ]
